name: Run tests

on: [push]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add wasm32-unknown-unknown
      
      - run: cargo build --release
      - run: cargo run_tests
